Pearson/pae 424
Pearson-Advance/frontend-app-custom-enrollment pull request #1
Opened 2021-03-03 22:00 UTC by ivanvgh

### Description:
This PR removes useless files from base template and adds the future folders and base files.

### Reviewers:

- [ ] @Squirrel18

2021-03-10 22:27 UTC, Squirrel18 requested changes

2021-03-10 22:27 UTC, Squirrel18 commented on src/components/common/PageContainer/index.jsx
> +  const colClasses = classNames('col', { 'col-xl-6 col-9': !props.wide });
Why are you using className? Is it necessary? @ivanvgh

2021-03-10 22:27 UTC, Squirrel18 commented on src/components/common/PageContainer/index.jsx
> +    <div className={containerClasses}>
Please use semantic HTML5 instead of generic divs. @ivanvgh

2021-03-10 22:27 UTC, Squirrel18 commented on src/components/common/PageContainer/index.jsx
> +  wide: PropTypes.bool,
What is this value used for? @ivanvgh

2021-03-10 22:27 UTC, Squirrel18 commented on src/containers/MainApp/index.jsx
> +  <div>
Please use semantic HTML5 instead of generic divs. @ivanvgh

2021-03-10 22:27 UTC, Squirrel18 commented on src/containers/MainApp/index.jsx
> +import React from 'react';
Since this is the entry point of the application I think you could place it in the root path of Components, what do you think? @ivanvgh

2021-03-10 22:27 UTC, Squirrel18 commented on src/data/constants/table.js
> +
Unnecessary blank line. @ivanvgh

2021-03-10 22:27 UTC, Squirrel18 commented on src/components/common/PageContainer/index.jsx
> +import './PageContainer.scss';
Add a blank line before this one to separate external modules from local modules. @ivanvgh

2021-03-10 22:27 UTC, Squirrel18 commented on src/data/reducers/table.js
> +} from '../constants/table';
I believe it's better to use absolute imports instead of relative imports. https://beqode.com/blog/absolute-vs-relative-import-paths-nodejs What do you think? @ivanvgh

2021-03-10 22:27 UTC, Squirrel18 commented on src/index.jsx
> +
Unnecessary blank line. @ivanvgh

2021-03-10 22:27 UTC, Squirrel18 commented on src/utils/formErrorParser/index.js
> +const getErrorMessages = (error) => {
What is this function used for? @ivanvgh

2021-03-10 22:27 UTC, Squirrel18 commented on src/components/common/PageContainer/index.jsx
> +import React from 'react';
Add doc-strings to all files as needed. @ivanvgh

2021-03-11 22:04 UTC, ivanvgh commented on package.json
> +    "classnames": "^2.2.6",
Is there a relationship between MFE requirements and the platform requirements?

2021-03-11 23:09 UTC, ivanvgh commented on src/components/common/PageContainer/index.jsx
> +  const colClasses = classNames('col', { 'col-xl-6 col-9': !props.wide });
It joins classes but in this case it is not necessary. Removed

2021-03-11 23:10 UTC, ivanvgh commented on src/components/common/PageContainer/index.jsx
> +    <div className={containerClasses}>
Done.

2021-03-11 23:26 UTC, ivanvgh commented on src/components/common/PageContainer/index.jsx
> +  wide: PropTypes.bool,
This value was thought to be for table wide, but in this case I think it can be removed.

2021-03-11 23:27 UTC, ivanvgh commented on src/containers/MainApp/index.jsx
> +  <div>
Done.

2021-03-11 23:32 UTC, ivanvgh commented on src/containers/MainApp/index.jsx
> +import React from 'react';
Yes it can be, but it think it is better inside the root path of containers folder since it is used as a container for the other components.

2021-03-11 23:32 UTC, ivanvgh commented on src/data/constants/table.js
> +
Removed.

2021-03-11 23:32 UTC, ivanvgh commented on src/components/common/PageContainer/index.jsx
> +import './PageContainer.scss';
Done.

2021-03-11 23:34 UTC, ivanvgh commented on src/data/reducers/table.js
> +} from '../constants/table';
Yes, I will give it a try.

2021-03-11 23:42 UTC, ivanvgh commented on src/index.jsx
> +
Removed.

2021-03-11 23:45 UTC, ivanvgh commented on src/utils/formErrorParser/index.js
> +const getErrorMessages = (error) => {
Currently it is not used but it will be used to map DRF form validation errors to its related fields as string validation error messages.

2021-03-11 23:54 UTC, ivanvgh commented on src/components/common/PageContainer/index.jsx
> +import React from 'react';
Done.

2021-03-13 06:00 UTC, Squirrel18 commented on src/utils/formErrorParser/index.js
> +const getErrorMessages = (error) => {
Ok, please add doc-strings to know what kind of data it receives and what kind of data it returns. @ivanvgh

2021-03-16 13:29 UTC, ivanvgh commented on package.json
> +    "classnames": "^2.2.6",
No, there should not be any conflict.

2021-03-16 14:38 UTC, ivanvgh commented on src/utils/formErrorParser/index.js
> +const getErrorMessages = (error) => {
Done.

2021-03-16 18:57 UTC, ivanvgh commented on src/components/common/PageContainer/index.jsx
> +    <div className="row justify-content-md-center">
They use Bootstrap's grid system.

2021-03-16 19:45 UTC, ivanvgh commented on src/data/history.js
> +const history = createBrowserHistory();
Because history is going to be used outside the components like utils folder, Nevertheless useHistory only allows to use the history inside of components.

2021-03-16 19:54 UTC, ivanvgh commented on src/data/store.js
> +import createRootReducer from './reducers';
This comes from reducers/index.js file, it is importing the exported by default unique method inside that file.

2021-05-04 12:23 UTC, ivanvgh commented on src/data/reducers/table.js
> +} from '../constants/table';
I've tried to configure it adding a 'jsconfig.json' file telling the baseurl is src folder but it didn't work, also tried 'NODE_PATH=src/' but still didn't work, read some documentation regarding this and it says this can be configured in webpack but since we use the edx MFE template it does not have this file, I think it is internally.

2021-05-28 20:29 UTC, ivanvgh commented
This PR was a pilot version for batch enrollments, the following ones are the official ones.

2021-05-28 20:29 UTC, closed without merging