Cleaning repo.
Pearson-Advance/frontend-app-custom-enrollment pull request #2
Opened 2021-05-21 13:05 UTC by ivanvgh

### Description:
This PR cleans the repository in order to use have only the necessary resources.

We decided to use hooks for PACO-MFE(Pearson Advance Course Operations MFE), so I've try to take off redux from the dependencies but I noticed that it is required by `<AppProvider />` component which is in charge of handling the authentication and some context data.

2021-05-25 06:36 UTC, Squirrel18 requested changes

2021-05-25 06:36 UTC, Squirrel18 commented on src/components/Dashboard/index.jsx
> +// To avoid default export warning(exporting in a different way won't render the dashboard content.)
Why not make Dashboard the default export? It's the only thing in this file... @ivanvgh

2021-05-25 06:36 UTC, Squirrel18 commented on src/components/MainApp/index.jsx
> +import React from 'react';
This does not need to be in a "MainApp" folder, because this is the main component that will contain others, so this could be placed in the components root directory. @ivanvgh

2021-05-25 06:36 UTC, Squirrel18 commented on src/components/MainApp/index.jsx
> +import { Dashboard } from '../Dashboard';
Please use absolute imports. @ivanvgh

2021-05-25 15:28 UTC, ivanvgh commented on src/components/Dashboard/index.jsx
> +// To avoid default export warning(exporting in a different way won't render the dashboard content.)
Updated to default export.

2021-05-25 15:29 UTC, ivanvgh commented on src/components/Dashboard/index.jsx
> +// To avoid default export warning(exporting in a different way won't render the dashboard content.)
Updated to default export and renamed to Enrollments.

2021-05-25 23:26 UTC, Squirrel18 requested changes

2021-05-25 23:26 UTC, Squirrel18 commented on .eslintrc.js
> +      }
Bad identation. @ivanvgh

2021-05-28 19:09 UTC, Squirrel18 approved these changes

2021-05-28 20:29 UTC, merged