View Enrollments, unenroll features.
Pearson-Advance/frontend-app-custom-enrollment pull request #3
Opened 2021-05-30 19:34 UTC by ivanvgh

### Description:
This PR adds view enrollments, and unenrollment features to Pearson Advance course operations MFE as described in the following tickets:
- [PAE-699](https://pearsonadvance.atlassian.net/browse/PAE-699?atlOrigin=eyJpIjoiZTJhMjUyYTFjOTUwNGJiM2I3ZDU4OWJjOWI4ZTY4ZjYiLCJwIjoiaiJ9)
- [PAE-701](https://pearsonadvance.atlassian.net/browse/PAE-701?atlOrigin=eyJpIjoiYjI3MGY1NzU3Nzc5NGIxZjkwYjY2MzM4ZjFkOTk4NDEiLCJwIjoiaiJ9)
![Screenshot from 2021-05-30 14-34-07](https://user-images.githubusercontent.com/36037715/120117716-278e8f80-c154-11eb-9d5c-d6f0883f080e.png)

2021-06-04 00:53 UTC, Squirrel18 requested changes

2021-06-04 00:53 UTC, Squirrel18 commented on .eslintrc.js
>  module.exports = createConfig('eslint', {
Add this plugin: https://www.npmjs.com/package/eslint-plugin-react-hooks to check hooks behaviour. @ivanvgh

2021-06-04 00:53 UTC, Squirrel18 commented on src/hooks/useForm.js
> +import { useState } from 'react';
I think this hook is not useful because:
1. Only used in one component.
2. It does not return any state, it returns some functions that modify the state.
3. You can't subscribe to this hook, you have to call the functions every time you need them.
Let me know what you think. @ivanvgh

2021-06-04 01:43 UTC, ivanvgh commented on .eslintrc.js
> +        "no-param-reassign": "off",
This was removed because in the reducers functions have the state parameters set with initialState values by default, that is why eslint is complaining but it is totally safe and necessary to initialize the state default value there. Also we are using arrow functions instead of the regular ones.

2021-06-07 14:46 UTC, ivanvgh commented on .eslintrc.js
>  module.exports = createConfig('eslint', {
Is this necessary? I've already removed the custom hook.

2021-06-07 14:46 UTC, ivanvgh commented on src/hooks/useForm.js
> +import { useState } from 'react';
Removed.

2021-06-07 14:47 UTC, ivanvgh commented on .eslintrc.js
> +        "react/prop-types": "off",
I am not using prop types.

2021-06-07 22:38 UTC, Squirrel18 requested changes

2021-06-07 22:38 UTC, Squirrel18 commented on src/components/App/index.jsx
> +  );
This should go in its own component module. @ivanvgh

2021-06-07 22:38 UTC, Squirrel18 commented on src/components/App/index.jsx
> +    <>
What's this for? @ivanvgh

2021-06-07 22:38 UTC, Squirrel18 commented on src/components/App/index.jsx
> +      <Container size="xl" className="my-4">
Where did you get "my-4" from? @ivanvgh

2021-06-07 22:38 UTC, Squirrel18 commented on src/components/App/index.jsx
> +          initialFilterValues={initialFilterValues}
I think Filters are not receiving initialFilterValues... @ivanvgh

2021-06-07 22:38 UTC, Squirrel18 commented on src/components/App/index.jsx
> +        <h3 className="title-wrapper">Enrollment Viewer</h3>
Mark the texts for translations even if we are not using it. @ivanvgh

2021-06-07 22:38 UTC, Squirrel18 commented on src/components/App/index.jsx
> +          handleClickClear={handleClickClear}
Is it necessary to pass event handlers to the component? You are not doing anything special with them. @ivanvgh

2021-06-07 22:38 UTC, Squirrel18 commented on src/components/App/index.scss
> +.title-wrapper{
Can't use the ".text-center" class to centre the text? @ivanvgh

2021-06-07 22:38 UTC, Squirrel18 commented on src/components/Filters/index.jsx
> +import React from 'react';
I think this component should be called: FilterForm or something like that, what do you think? @ivanvgh

2021-06-07 22:38 UTC, Squirrel18 commented on src/components/Table/index.jsx
> +  const enrollmentTableColumns = [
This can be placed in another file to avoid boilerplate code here. @ivanvgh

2021-06-08 03:32 UTC, ivanvgh commented on .eslintrc.js
> +        "react/prop-types": "off",
Yes, eslint complains about this rule.

2021-06-08 03:36 UTC, ivanvgh commented on .eslintrc.js
> +        "no-param-reassign": "off",
Because I try to use them in order to have compact code and more readability, in case we need to use regular functions then I will choose them.

P.S. Even if I use regular functions this rule will be set to off as I mention in the previous reply.

2021-06-08 03:42 UTC, ivanvgh commented on src/components/App/index.jsx
> +    <>
The empty tags are used to wrap the component children, like react fragments `<React.Fragment>` or `<div>`.

2021-06-08 03:46 UTC, ivanvgh commented on src/components/App/index.jsx
> +      <Container size="xl" className="my-4">
Those are bootstrap spacing utilities classes. Paragon uses them.

2021-06-08 03:59 UTC, ivanvgh commented on src/components/App/index.jsx
> +          handleClickClear={handleClickClear}
I am trying to maintain the logic with dispatchers in the app component. What do you think @Squirrel18?

2021-06-08 04:08 UTC, ivanvgh commented on src/components/Table/index.jsx
> +  const enrollmentTableColumns = [
The table columns are part of the table, and might go in the same file since there are special column mappings that access to the row values. Does it make sense @Squirrel18 ?

2021-06-08 04:15 UTC, ivanvgh commented on src/components/App/index.jsx
> +  );
I think it is not necessary to create a component for another component, but what I can do is to remove this const ToastMessage and directly render it in the return statement. What do you think @Squirrel18 ?

2021-06-08 04:17 UTC, ivanvgh commented on src/components/App/index.jsx
> +        <h3 className="title-wrapper">Enrollment Viewer</h3>
Do you think it is worth since this MFE is only for Pearson admin staff?

2021-06-08 18:45 UTC, Squirrel18 requested changes

2021-06-08 18:45 UTC, Squirrel18 commented on .eslintrc.js
> +        "react/prop-types": "off",
Ok, so you should use proptypes unless you have a better reason not to. @ivanvgh 
Ref: https://stackoverflow.com/questions/54296313/proptypes-for-custom-react-hooks, https://github.com/edx/frontend-app-course-authoring/blob/bc586a0b8d6cd05ca1960d05abfb43a331989360/src/CourseAuthoringPage.jsx, https://blog.logrocket.com/practical-react-hooks-how-to-refactor-your-app-to-use-hooks-b1867e7b0a53/

2021-06-08 18:45 UTC, Squirrel18 commented on .eslintrc.js
> +        "no-param-reassign": "off",
So please disable this warning in the places you think you need rather than disable it globally. @ivanvgh

2021-06-08 18:45 UTC, Squirrel18 commented on .eslintrc.js
> +        "import/no-extraneous-dependencies": "off",
Where are you importing undeclared dependencies? @ivanvgh

2021-06-08 18:45 UTC, Squirrel18 commented on .eslintrc.js
> +        "react/jsx-filename-extension": "off",
For which file are you disabling this rule? @ivanvgh

2021-06-08 18:45 UTC, Squirrel18 commented on .eslintrc.js
> +        "jsx-a11y/anchor-is-valid":"off",
Why did you disable this one? @ivanvgh

2021-06-08 18:45 UTC, Squirrel18 commented on src/components/App/index.jsx
> +    <>
I think it is not necessary here because it contains the rest of the components and is rendered on the router. Is there an error if you remove it? @ivanvgh

2021-06-08 18:45 UTC, Squirrel18 commented on src/components/App/index.jsx
> +      <Container size="xl" className="my-4">
What if you don't add it? Seems weird... @ivanvgh

2021-06-08 18:45 UTC, Squirrel18 commented on src/components/App/index.jsx
> +          handleClickClear={handleClickClear}
Then you have to add memoized capabilities to the dispatcher: https://react-redux.js.org/api/hooks#usedispatch I think it is better to handle these events in the component itself unless you need to add custom functionality to these events. @ivanvgh

2021-06-08 20:37 UTC, ivanvgh commented on src/components/App/index.jsx
> +    <>
Alright, I got you, then I am removing this fragment.

2021-06-08 20:46 UTC, ivanvgh commented on src/components/App/index.jsx
> +      <Container size="xl" className="my-4">
This one sets margin 3 for top and bottom, actually paragon commonly uses this utilities: https://paragon-edx.netlify.app/foundations/spacing.

2021-06-08 21:01 UTC, ivanvgh commented on src/components/App/index.jsx
> +          handleClickClear={handleClickClear}
I am moving this to its component.

2021-06-08 21:52 UTC, ivanvgh commented on .eslintrc.js
> +        "import/no-extraneous-dependencies": "off",
Probably in webpack config files 'path', but it complains in all files first lines even if there is nothing imported like data/types.js. This one is also disable in  other edx's [mfes](https://github.com/edx/frontend-app-learning/blob/master/.eslintrc.js#L8).

2021-06-08 21:57 UTC, ivanvgh commented on .eslintrc.js
> +        "react/jsx-filename-extension": "off",
For all data/* files.

2021-06-08 22:07 UTC, ivanvgh commented on .eslintrc.js
> +        "jsx-a11y/anchor-is-valid":"off",
Same as the 'import/no-extraneous-dependencies' I think it is a false positive, that is why I am disabling it.

2021-07-03 01:41 UTC, Squirrel18 requested changes

2021-07-03 01:41 UTC, Squirrel18 commented on src/components/EnrollmentsList/index.jsx
> +    <div className="enrollments-container">
Use HTML5 semantic elements. @ivanvgh

2021-07-03 01:41 UTC, Squirrel18 commented on src/components/EnrollmentsList/index.jsx
> +const EnrollmentsList = () => {
Why aren't you using PropTypes? @ivanvgh

2021-07-03 01:41 UTC, Squirrel18 commented on src/components/EnrollmentsTable/columns.js
> +        ]
Trailing comma. @ivanvgh

2021-07-03 01:41 UTC, Squirrel18 commented on src/components/EnrollmentsTable/index.jsx
> +  const columns = useMemo(() => COLUMNS, []);
I believe that "useMemo" has no effect here because it doesn't depend on any other value. @ivanvgh

2021-07-03 01:41 UTC, Squirrel18 commented on src/components/EnrollmentsTable/index.jsx
> +    <div className="enrollments-container">
Use HTML5 sematic elements. @ivanvgh

2021-07-03 01:41 UTC, Squirrel18 commented on src/components/EnrollmentsTable/index.jsx
> +export { EnrollmentsTable };
Missing file end line. @ivanvgh

2021-07-03 01:41 UTC, Squirrel18 commented on src/components/EnrollmentsTable/index.scss
> +    flex-grow: 1;
Add a blank line after this line to separate CSS definitions. @ivanvgh

2021-07-03 01:41 UTC, Squirrel18 commented on src/components/EnrollmentsTable/index.scss
> +    tr td {
I think this definition can be nested inside the table definition. @ivanvgh

2021-07-03 01:41 UTC, Squirrel18 commented on src/components/EnrollmentsTable/index.scss
> +.page-size-selector {
Where is this used? @ivanvgh

2021-07-05 14:34 UTC, ivanvgh commented on src/components/EnrollmentsList/index.jsx
> +const EnrollmentsList = () => {
Because it does not receive props.That is why es-lint does not complain about it as well.

2021-07-05 14:53 UTC, ivanvgh commented on src/components/EnrollmentsTable/index.jsx
> +  const columns = useMemo(() => COLUMNS, []);
This was taken from the docs: https://react-table.tanstack.com/docs/api/useTable#table-options

2021-07-05 14:57 UTC, ivanvgh commented on src/components/EnrollmentsTable/index.scss
> +.page-size-selector {
Actually, this is for pagination, i will remove it to avoid misunderstandings.

2021-07-05 15:19 UTC, ivanvgh commented on .eslintrc.js
> +        "jsx-a11y/anchor-is-valid":"off",
Actually, I'm not using it, I believe the problem is with this package `eslint-plugin-react-hooks`, when I enable this `it` shows the following:
`error  Definition for rule 'jsx-a11y/anchor-is-valid' was not found  jsx-a11y/anchor-is-valid`

And if add a rule e.g.:

`"jsx-a11y/anchor-is-valid": ["error", {
            "components": ["Link"],
            "specialLink": ["to"]
        }],`
Still the same error, Probably it is not the right plugin, What do you think @Squirrel18?

2021-07-05 20:12 UTC, ivanvgh commented on .eslintrc.js
> +        "jsx-a11y/anchor-is-valid":"off",
Rule disabled.

2021-07-06 02:13 UTC, Squirrel18 requested changes

2021-07-06 02:13 UTC, Squirrel18 commented on src/data/actions/enrollment.js
> +  EnrollmentDataApiService.fetchEnrollments(pageSize, pageIndex, filters)
Let's use async/await functionality: https://redux.js.org/tutorials/fundamentals/part-6-async-logic instead of a promise-related one.  @ivanvgh

2021-07-06 02:13 UTC, Squirrel18 commented on src/data/actions/enrollment.js
> +import {
These definitions in this file are not actions, they must be treated as "Features": https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers#splitting-reducers. @ivanvgh

2021-07-06 02:21 UTC, ivanvgh commented on package.json
> +    "query-string": "^6.12.1",
Actually, this one is not being used, It'll be removed.

2021-07-08 04:26 UTC, Squirrel18 requested changes

2021-07-08 04:26 UTC, Squirrel18 commented on src/components/FilterForm/index.jsx
> +    e.preventDefault();
Add a blank line after this line. @ivanvgh

2021-07-08 04:26 UTC, Squirrel18 commented on src/components/FilterForm/index.jsx
> +    };
Add a blank line after this line. @ivanvgh

2021-07-08 04:26 UTC, Squirrel18 commented on src/data/actions/enrollmentCreator.js
> +      filters,
Add a named parameter for this value. @ivanvgh

2021-07-08 04:26 UTC, Squirrel18 commented on src/data/services/dataApi.js
> +const enrollmentBaseUrl = `${process.env.ENROLLMENT_API_BASE_URL}/api/v1`;
Please get the full URL value from the settings, not just the domain. @ivanvgh

2021-07-08 04:26 UTC, Squirrel18 commented on src/data/services/dataApi.js
> +  const url = `${enrollmentBaseUrl}/course-enrollment`;
You can remove these variables as they are only used once. @ivanvgh

2021-07-08 04:26 UTC, Squirrel18 commented on src/index.jsx
> +      <Footer className="footer" />
Why did you add the class "footer"? @ivanvgh

2021-07-08 04:26 UTC, Squirrel18 commented on src/utils/index.js
> +const addPeriodToString = (string) => {
Where will errors be logged?
Because I think there is no need to format an error message that will not be displayed to the end user. @ivanvgh

2021-07-08 04:26 UTC, Squirrel18 commented on webpack.dev.config.js
> +      hooks: path.resolve(__dirname, 'src/hooks'),
This is no longer used. @ivanvgh

2021-07-08 04:26 UTC, Squirrel18 commented on webpack.prod.config.js
> +      hooks: path.resolve(__dirname, 'src/hooks'),
This is no longer used. @ivanvgh

2021-07-08 18:37 UTC, ivanvgh commented on src/index.jsx
> +      <Footer className="footer" />
I'll remove.

2021-07-08 18:42 UTC, ivanvgh commented on src/utils/index.js
> +const addPeriodToString = (string) => {
Actually this is used to format the error messages on `src/data/actions/enrollmentCreator.js`, This message will be shown as Toast messages on the UI, but this UI functionality will be added in the following PR.

2021-07-09 02:25 UTC, Squirrel18 requested changes

2021-07-09 02:25 UTC, Squirrel18 commented on src/data/services/dataApi.js
> +
Unnecessary blank line. @ivanvgh

2021-07-09 02:25 UTC, Squirrel18 commented on src/data/services/dataApi.js
> +const enrollmentBaseUrl = `${process.env.ENROLLMENT_API_BASE_URL}`;
I think we can get rid of this variable since it's only used once. @ivanvgh

2021-07-09 02:25 UTC, Squirrel18 commented on src/data/services/dataApi.js
> +  const url = `${enrollmentBaseUrl}/course-enrollment`;
I think we can get rid of this variable since it's only used once. @ivanvgh

2021-07-09 02:25 UTC, Squirrel18 commented on src/data/actions/enrollmentCreator.js
> +    const response = await fetchEnrollments(pageSize, pageIndex, filters);
Please add a blank line after this line. @ivanvgh

2021-07-09 02:25 UTC, Squirrel18 commented on src/utils/index.js
> +const addPeriodToString = (string) => {
So please add a doc-string (with examples) to these functions to know what exactly they do. @ivanvgh

2021-07-09 02:25 UTC, Squirrel18 commented on src/utils/index.js
> +    const punctuation = new Set(['.', ',', ':', '!', '?']);
This variable is only used once. @ivanvgh

2021-07-09 02:25 UTC, Squirrel18 commented on src/utils/index.js
> +  return string;
```suggestion
      return string;
    }
    
    return `${string}.`;
  }
  
  return string;
```

2021-07-09 02:25 UTC, Squirrel18 commented on src/utils/index.js
> +const getErrorMessages = (error) => {
Could you try to simplify this function? It's really confusing and doesn't make a lot of sense. @ivanvgh

2021-07-09 14:39 UTC, ivanvgh commented on src/data/actions/enrollmentCreator.js
> +    const response = await fetchEnrollments(pageSize, pageIndex, filters);
@Squirrel18, can you share the styleguide we are using?

2021-07-09 15:29 UTC, ivanvgh commented on src/utils/index.js
> +    const punctuation = new Set(['.', ',', ':', '!', '?']);
This method was removed since this function was refactored.

2021-07-09 15:30 UTC, ivanvgh commented on src/utils/index.js
> +  return string;
Code removed due to code refactor.

2021-07-09 21:59 UTC, Squirrel18 commented on src/data/actions/enrollmentCreator.js
> +    const response = await fetchEnrollments(pageSize, pageIndex, filters);
Frontend-build, Airbnb. @ivanvgh

2021-07-09 22:23 UTC, Squirrel18 requested changes

2021-07-09 22:23 UTC, Squirrel18 commented on src/utils/index.js
> + * @returns {String}     Properly formated field error message.
```suggestion
 * @param {object} Error response.
 * @returns {String} Properly formated field error message.
```

2021-07-09 22:29 UTC, ivanvgh commented on src/utils/index.js
> + * @returns {String}     Properly formated field error message.
Removing blank spaces but not 'error' since that is the parameter name:
` * @param {object} error Error response.
 * @returns {String} Properly formated field error message.`

2021-08-05 00:06 UTC, Squirrel18 requested changes

2021-08-05 00:06 UTC, Squirrel18 commented on src/utils/index.js
> +  // For generic Http errors like 500, 404 that does not contain field validation
```suggestion
  // For generic HTTP errors like 500, 404 that does not contain field validation.
```

2021-08-05 00:06 UTC, Squirrel18 commented on src/utils/index.js
> +  // error messages.
```suggestion
  // Error messages.
```

2021-08-05 00:15 UTC, ivanvgh commented on src/utils/index.js
> +  // error messages.
It is part of the previous line, I'll keep it in one line.

2021-08-06 04:46 UTC, Squirrel18 commented on src/components/EnrollmentsTable/index.scss
> +.enrollments-container {
This class is used in: src/components/EnrollmentList/index.jsx not in EnrollmentsTable. @ivanvgh

2021-08-10 03:47 UTC, Squirrel18 approved these changes

2021-08-10 04:00 UTC, merged