pearson/PAE-701  Unenroll user from a course_id using the MFE.
Pearson-Advance/frontend-app-custom-enrollment pull request #5
Opened 2022-01-04 16:11 UTC by anfbermudezme

WIP: The approach of this feature is to unenroll user from a course_id using the MFE.

The intention is add other column with a button for each course_id when the filter is applied.

![image](https://user-images.githubusercontent.com/30726391/151072464-ed3cba1b-abfd-464a-84e6-c8fef7f3a398.png)

When the Button is clicked appear an AlertModal asking 'Are you sure you want to unenroll?' and If you select cancel nothing happens but If you select Submit user will be deactivated from the course_id. 

![Selection_324](https://user-images.githubusercontent.com/30726391/153926287-4bc2065c-8c30-44fc-ada1-abe4d9b4c757.png)

Also when the unroll is successfully, message appear and It can be seen that the state of is_active changes. 

![Selection_325](https://user-images.githubusercontent.com/30726391/153926304-394bf45f-16d3-47ab-bc87-60c4d7184bce.png)

When user is not enrolled in a course_id, the Button show Enroll but for now this Button should do nothing.

![Selection_329](https://user-images.githubusercontent.com/30726391/154084578-42509e48-3fb6-4238-a038-e5ae105f20c7.png)

2022-01-07 21:24 UTC, ivanvgh requested changes

2022-01-07 21:24 UTC, ivanvgh commented on src/components/EnrollmentsTable/columns.jsx
> +      const handleClickUnenroll = (data) => dispatch(unenrollAction(data));
@anfbermudezme, you should keep this logic in the parent component and pass it to this one, I mean you can make this a function and receive the method as an argument of `[this](https://github.com/Pearson-Advance/frontend-app-pearson-admin-portal/blob/master/src/features/institutions/components/InstitutionsTable/columns.jsx#L8)` component.

2022-01-07 21:24 UTC, ivanvgh commented on src/components/EnrollmentsTable/columns.jsx
> +              If you select cancel nothing happens but If you select Submit user will be deactivated from the course_id.
I guess we don't need to explain what cancel does. Also, let the user that will be unenrolled not deactivated. Does that make sense @anfbermudezme?

2022-01-07 21:24 UTC, ivanvgh commented on src/data/actions/enrollmentCreator.js
> +    const response = await EnrollmentDataApiService.fetchEnrollments(pageSize, pageIndex, filters);
```suggestion
    const response = await fetchEnrollments(pageSize, pageIndex, filters);
```

2022-01-07 21:24 UTC, ivanvgh commented on src/data/actions/enrollmentCreator.js
> +    const response = await EnrollmentDataApiService.fetchEnrollments(pageSize, pageIndex, filters);
Is there any reason you changed this?

2022-01-07 21:24 UTC, ivanvgh commented on src/data/actions/unenrollmentCreator.js
> +import { EnrollmentDataApiService } from 'data/services/dataApi';
@anfbermudezme, let's import only the necessary methods.

2022-01-07 21:24 UTC, ivanvgh commented on src/data/reducers/enrollment.js
> +        return item
@anfbermudezme, could you add a blank line before the return line?

2022-01-07 21:24 UTC, ivanvgh commented on src/data/reducers/enrollment.js
> +      var deepCopy = _.cloneDeep(state.data);
```suggestion
      const dataCopy = _.cloneDeep(state.data);
```

2022-01-07 21:24 UTC, ivanvgh commented on src/data/reducers/enrollment.js
> +      })
@anfbermudezme, let's add a blank line before the return line, please. This is to make it more readable.

2022-01-07 21:24 UTC, ivanvgh commented on src/data/services/dataApi.js
> +    const url = `${process.env.ENROLLMENT_API_BASE_URL}/batch-enrollment`;
@anfbermudezme, this variable is only used once, you can remove it and use the value directly.

2022-01-07 21:24 UTC, ivanvgh commented on src/data/services/dataApi.js
> +    // POST request to make an unenrollment
```suggestion
    // POST request to make an unenrollment.
```

2022-01-07 21:24 UTC, ivanvgh commented on src/data/services/dataApi.js
> +    // POST to Course endpoint to create
```suggestion
    // POST to Course endpoint to create.
```

2022-01-07 21:24 UTC, ivanvgh commented on src/data/services/dataApi.js
> +    const url = `${process.env.ENROLLMENT_API_BASE_URL}/task-status`;
@anfbermudezme, these variables are only used once, let's remove them, please.

2022-01-07 21:24 UTC, ivanvgh commented on src/data/reducers/enrollment.js
> +import * as _ from 'lodash';
@anfbermudezme, let's import only the method that we need.

2022-01-07 21:24 UTC, ivanvgh commented on src/data/reducers/enrollment.js
> +      const newState = deepCopy.map(item => {
@anfbermudezme, to avoid confusion, let's rename this variable to `newData`, what do you think about it?

2022-01-10 20:34 UTC, anfbermudezme commented on src/data/actions/enrollmentCreator.js
> +    const response = await EnrollmentDataApiService.fetchEnrollments(pageSize, pageIndex, filters);
The reason is that EnrollmentDataApiService is a class with the functions about unenrollment and the intention is in the other ticket regarding enrollment add the functionality inside this class.

2022-01-17 15:29 UTC, ivanvgh requested changes
@anfbermudezme, there are some warnings to address, please check them out.

2022-01-17 15:29 UTC, ivanvgh commented on src/components/EnrollmentsTable/columns.jsx
> +          </Toast>
@anfbermudezme, did you check a way to move this component to its parent? if we leave it like it is, this component would be rendered as many rows as we have and it does not make sense.

2022-01-17 15:29 UTC, ivanvgh commented on src/components/EnrollmentsTable/columns.jsx
> +          </AlertModal>
@anfbermudezme, did you check a way to move this component to its parent? *Same as the Toast component.

2022-01-17 15:29 UTC, ivanvgh commented on src/components/EnrollmentsTable/columns.jsx
> +            Unenroll Successfully !
@anfbermudezme, I think it could be:
```suggestion
            Successfully unenrolled!
```

2022-01-17 15:29 UTC, ivanvgh commented on src/components/EnrollmentsTable/columns.jsx
> +              Selecting Submit will unenroll the user from Course ID.
```suggestion
              Once submitted the user will be unenrolled from the course.
```

2022-01-17 15:29 UTC, ivanvgh commented on src/data/actions/enrollmentCreator.js
> +    const response = await EnrollmentDataApiService.fetchEnrollments(pageSize, pageIndex, filters);
I think we can keep only the methods in this case.

2022-01-31 12:25 UTC, ivanvgh requested changes

2022-01-31 12:25 UTC, ivanvgh commented on src/components/EnrollmentsTable/index.jsx
> +import { unenrollAction } from '../../data/actions/unenrollmentCreator';
@anfbermudezme, please use absolute imports.

2022-01-31 12:25 UTC, ivanvgh commented on src/components/EnrollmentsTable/index.jsx
> +    setRow({});
@anfbermudezme, I guess this is unnecessary, could you try removing it out, please?

2022-01-31 12:25 UTC, ivanvgh commented on src/components/EnrollmentsTable/index.jsx
> +        show={Boolean(show)}
@anfbermudezme, is it necessary to convert it since ist is already a boolean?

2022-01-31 12:25 UTC, ivanvgh commented on src/data/reducers/enrollment.js
> +  UNENROLL_FAILURE,
Since you are splitting the unenrollment and the enrollment creators you should split the reducers as well.

2022-01-31 12:25 UTC, ivanvgh commented on src/data/reducers/enrollment.js
> +        dataTotalCount: 0,
Why do you empty the data when unenrollment is failed? I guess that is not necessary. The toast message should show the error and the data should remain the same.

2022-01-31 12:25 UTC, ivanvgh commented on src/data/services/dataApi.js
> +export { createUnenrollment, fetchEnrollments };
```suggestion
export { 
  createUnenrollment,
  fetchEnrollments,
};
```

2022-02-07 16:38 UTC, ivanvgh approved these changes

2022-02-15 13:27 UTC, Jacatove requested changes
I suppose there should be an "Enroll"" action, if the enrollment is not active, that correct?. 
![image](https://user-images.githubusercontent.com/40271196/154071043-f7883cd0-60be-4a24-835d-601884b8ae44.png)

2022-02-15 13:27 UTC, Jacatove commented on public/index.html
> +      <title>Pearson Custom Enrollments | <%= process.env.SITE_NAME %></title>
I wonder why did you call it Custom Enrollments?, aren't they Course Enrollments?. @anfbermudezme

2022-02-15 14:47 UTC, Jacatove approved these changes

2022-02-15 16:23 UTC, merged